version: "3.9"  # optional since v1.27.0
services:
    nginx:
        build: ./requirements/nginx/
        ports:
            - "22:22"
            - "80:80"
            - "443:443"
        hostname: salec
        domainname: salec.42.fr
        networks:
            - inception
        extra_hosts:
            - "salec.42.fr:127.0.0.1"

networks:
    inception:
        driver: bridge
