version: "3.9"  # optional since v1.27.0
volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/${USER}/data/db
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: volume
      device: /home/${USER}/data/wp
      o: bind

networks:
  inception:

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    hostname: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - "mariadb-data:/var/lib/mysql"
    restart: on-failure
    init: true
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    hostname: wordpress
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - "wordpress-data:/var/www/localhost/htdocs/wordpress"
    restart: on-failure
    init: true
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    hostname: nginx
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    networks:
      - inception
    extra_hosts:
      - "arcticfox.42.fr:127.0.0.1"
    volumes:
      - "wordpress-data:/var/www/localhost/htdocs/wordpress"
    restart: on-failure
    init: true
